filenames={'/Volumes/My Passport/Holly Grey/Model 1/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 2/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 3/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 4/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 5/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 6/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 7/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 8/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 9/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 10/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 11/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 12/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 13/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 14/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 15/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 16/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 17/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 18/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 19/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 20/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 21/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 22/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 23/output.nc', ...
'/Volumes/My Passport/Holly Grey/Model 24/output.nc'};

semi_major=[300 300 300 500 500 500 700 700 700 700 700 600 600 600 600 550 550 550 650 650 650 650 650 650];
mass=[5 10 15 5 10 15 5 10 15 12.5 13.75 5 10 7.5 8.75 7.5 10 8.75 10 15 12.5 20 17.5 18.75];

fraction_clust=zeros(24,1);

for jj=1:24
    orbit_properties;
    fraction_clust(jj)=fraction_of_clustering;
end

figure;

scatter(semi_major,mass,200,fraction_clust,'filled')
xlabel('Semi Major Axis (AU)');
ylabel('Mass (earth masses)');
h=colorbar
ylabel(h,'Fraction of significant clusters');




figure;
XI=300:50:700;
YI=5:5:20;
ZI=griddata(semi_major,mass,fraction_clust,XI,YI')
contourf(XI,YI,ZI);shading flat






